"""
Nautilus Code Generator
Generates production-grade NautilusTrader strategy code from configuration
Reference: docs/v3/UI-UX/31_NAUTILUS_CODE_GENERATION.md
"""

import ast
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime

from src.strategy_builder.core.strategy_config_engine import StrategyConfig


@dataclass
class GeneratedCode:
    """Generated strategy code and configuration"""
    strategy_code: str
    config_dict: Dict[str, Any]
    file_name: str
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class CodeValidationResult:
    """Result of code syntax validation"""
    is_valid: bool
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)


class NautilusCodeGenerator:
    """
    Generates production-grade NautilusTrader strategy code
    Ensures type safety, proper enums, and institutional-grade quality
    """
    
    def __init__(self):
        """Initialize code generator"""
        self.indent = "    "  # 4 spaces
        
    def generate(self, config: StrategyConfig) -> GeneratedCode:
        """
        Generate complete strategy code from configuration
        
        Args:
            config: Strategy configuration
            
        Returns:
            GeneratedCode with strategy code and config
        """
        # Generate each section
        imports = self._generate_imports()
        class_def = self._generate_class_definition(config)
        init_method = self._generate_init_method(config)
        on_start = self._generate_on_start(config)
        on_bar = self._generate_on_bar(config)
        helper_methods = self._generate_helper_methods(config)
        
        # Combine all sections
        strategy_code = "\n\n".join([
            imports,
            class_def,
            init_method,
            on_start,
            on_bar,
            helper_methods
        ])
        
        # Generate config dict
        config_dict = self._generate_config_dict(config)
        
        # Generate file name
        file_name = self._generate_file_name(config)
        
        return GeneratedCode(
            strategy_code=strategy_code,
            config_dict=config_dict,
            file_name=file_name,
            metadata={
                'generated_at': datetime.now().isoformat(),
                'blocks_count': len(config.blocks),
                'required_signals': config.required_signals
            }
        )
        
    def _generate_imports(self) -> str:
        """Generate import statements"""
        return '''"""
Auto-generated NautilusTrader Strategy
Generated by BTC_Engine_v3 Strategy Builder
DO NOT EDIT MANUALLY - Regenerate through Strategy Builder
"""

from nautilus_trader.trading.strategy import Strategy
from nautilus_trader.model.data import Bar
from nautilus_trader.model.enums import OrderSide, TimeInForce
from nautilus_trader.model.identifiers import InstrumentId
from nautilus_trader.model.instruments import Instrument
from nautilus_trader.model.orders import MarketOrder
from nautilus_trader.core.datetime import unix_nanos_to_dt
from nautilus_trader.core.data import Data
from typing import Dict, List, Optional
from decimal import Decimal'''
        
    def _generate_class_definition(self, config: StrategyConfig) -> str:
        """Generate class definition with docstring"""
        class_name = config.name or "GeneratedStrategy"
        description = config.description or "Auto-generated strategy"
        
        code = f'''class {class_name}(Strategy):
    """
    {description}
    
    Auto-generated by BTC_Engine_v3 Strategy Builder
    
    Building Blocks:'''
        
        for block in config.blocks:
            logic_str = "REQUIRED (AND)" if block.logic == "AND" else "OPTIONAL (OR)"
            code += f"\n    - {block.name} ({logic_str})"
            
        code += f'''
    
    Required Signals: {config.required_signals}
    """'''
        
        return code
        
    def _generate_init_method(self, config: StrategyConfig) -> str:
        """Generate __init__ method"""
        code = f'''{self.indent}def __init__(self, config: Dict[str, Any]):
{self.indent * 2}"""Initialize strategy with configuration"""
{self.indent * 2}super().__init__(config)
{self.indent * 2}
{self.indent * 2}# Strategy configuration
{self.indent * 2}self.instrument_id = InstrumentId.from_str(config.get("instrument_id", "BTC/USDT.BINANCE"))
{self.indent * 2}self.bar_type = config.get("bar_type", "15-MINUTE")
{self.indent * 2}
{self.indent * 2}# Signal tracking
{self.indent * 2}self.signal_state: Dict[str, int] = {{}}  # signal_name -> bar_index
{self.indent * 2}self.required_signals = {config.required_signals}
{self.indent * 2}self.current_bar_index = 0
{self.indent * 2}self.strategy_type = config.get("strategy_type", "Bullish")
{self.indent * 2}
{self.indent * 2}# Building block configuration'''
        
        # Add block configurations
        for block in config.blocks:
            code += f"\n{self.indent * 2}self.block_{block.name.lower()}_enabled = True"
            
        return code
        
    def _generate_on_start(self, config: StrategyConfig) -> str:
        """Generate on_start method"""
        code = f'''{self.indent}def on_start(self):
{self.indent * 2}"""Called when strategy starts"""
{self.indent * 2}self.log.info(f"Starting {{self.__class__.__name__}}")
{self.indent * 2}
{self.indent * 2}# Subscribe to bars
{self.indent * 2}self.subscribe_bars(self.bar_type)
{self.indent * 2}
{self.indent * 2}# Initialize signal tracking
{self.indent * 2}self.signal_state = {{}}
{self.indent * 2}self.current_bar_index = 0
{self.indent * 2}self.log.info("Strategy initialization complete")'''
        
        return code
        
    def _generate_on_bar(self, config: StrategyConfig) -> str:
        """Generate on_bar method with strategy logic"""
        code = f'''{self.indent}def on_bar(self, bar: Bar):
{self.indent * 2}"""Process each bar and check for signals"""
{self.indent * 2}self.current_bar_index += 1
{self.indent * 2}
{self.indent * 2}# Check each building block'''
        
        for block in config.blocks:
            code += f"\n{self.indent * 2}self._check_{block.name.lower()}(bar)"
            
        code += f'''
{self.indent * 2}
{self.indent * 2}# Check if strategy conditions met
{self.indent * 2}if self._strategy_conditions_met():
{self.indent * 2}    self._execute_trade(bar)
{self.indent * 2}
{self.indent * 2}# Check timing constraints and reset if needed
{self.indent * 2}if self._should_reset_strategy():
{self.indent * 2}    self.signal_state = {{}}'''
        
        return code
        
    def _generate_helper_methods(self, config: StrategyConfig) -> str:
        """Generate helper methods"""
        code = ""
        
        # Generate check methods for each block
        for block in config.blocks:
            block_method = f'''{self.indent}def _check_{block.name.lower()}(self, bar: Bar):
{self.indent * 2}"""Check {block.name} building block signals"""
{self.indent * 2}if not self.block_{block.name.lower()}_enabled:
{self.indent * 2}    return
{self.indent * 2}
{self.indent * 2}# TODO: Implement {block.name} signal detection
{self.indent * 2}# This would check for:'''
            
            for signal in block.signals:
                block_method += f"\n{self.indent * 2}# - {signal.name}"
                
            block_method += f"\n{self.indent * 2}pass"
            code += "\n\n" + block_method
            
        # Strategy conditions method
        code += f'''
    
{self.indent}def _strategy_conditions_met(self) -> bool:
{self.indent * 2}"""Check if all required strategy conditions are met"""
{self.indent * 2}# Count AND signals (required)
{self.indent * 2}and_signals_met = 0
{self.indent * 2}
{self.indent * 2}for signal_name, bar_index in self.signal_state.items():
{self.indent * 2}    if "AND" in signal_name.upper():  # Simplified logic
{self.indent * 2}        and_signals_met += 1
{self.indent * 2}
{self.indent * 2}return and_signals_met >= self.required_signals
    
{self.indent}def _should_reset_strategy(self) -> bool:
{self.indent * 2}"""Check if strategy should reset due to timing violations"""
{self.indent * 2}# TODO: Implement timing constraint checking
{self.indent * 2}# Would check if signals fired outside their timing windows
{self.indent * 2}return False
    
{self.indent}def _execute_trade(self, bar: Bar):
{self.indent * 2}"""Execute trade when conditions are met"""
{self.indent * 2}self.log.info(f"Strategy conditions met at bar {{self.current_bar_index}}")
{self.indent * 2}
{self.indent * 2}# Determine order side based on strategy type
{self.indent * 2}order_side = OrderSide.BUY if self.strategy_type == "Bullish" else OrderSide.SELL  # Inferred from strategy_type
{self.indent * 2}
{self.indent * 2}# Create order with proper types
{self.indent * 2}from nautilus_trader.model.objects import Quantity, Price
{self.indent * 2}quantity = Quantity.from_str("0.001")  # TODO: Calculate position size
{self.indent * 2}
{self.indent * 2}# Submit market order
{self.indent * 2}order = self.order_factory.market(
{self.indent * 2}    instrument_id=self.instrument_id,
{self.indent * 2}    order_side=order_side,
{self.indent * 2}    quantity=quantity,
{self.indent * 2})
{self.indent * 2}
{self.indent * 2}self.submit_order(order)
{self.indent * 2}
{self.indent * 2}# Reset signal state after trade
{self.indent * 2}self.signal_state = {{}}'''
        
        return code
        
    def _generate_config_dict(self, config: StrategyConfig) -> Dict[str, Any]:
        """Generate strategy configuration dictionary"""
        config_dict = {
            "strategy_name": config.name or "GeneratedStrategy",
            "instrument_id": "BTC/USDT.BINANCE",
            "bar_type": "15-MINUTE",
            "strategy_type": config.strategy_type,
            "required_signals": config.required_signals,
            "blocks": []
        }
        
        for block in config.blocks:
            block_config = {
                "name": block.name,
                "logic": block.logic,
                "enabled": True,
                "signals": []
            }
            
            for signal in block.signals:
                signal_config = {
                    "name": signal.name,
                    "logic": signal.logic
                }
                if signal.timing_constraint:
                    signal_config["timing_constraint"] = {
                        "max_candles": signal.timing_constraint.max_candles,
                        "reference": signal.timing_constraint.reference
                    }
                block_config["signals"].append(signal_config)
                
            config_dict["blocks"].append(block_config)
            
        return config_dict
        
    def _generate_file_name(self, config: StrategyConfig) -> str:
        """Generate appropriate file name"""
        name = config.name or "generated_strategy"
        # Convert to snake_case
        name = name.replace(" ", "_").lower()
        return f"{name}.py"
        
    def validate_syntax(self, code: str) -> CodeValidationResult:
        """
        Validate Python syntax of generated code
        
        Args:
            code: Python code to validate
            
        Returns:
            CodeValidationResult with validation status
        """
        errors = []
        warnings = []
        
        try:
            # Parse code to check syntax
            ast.parse(code)
            
            # Additional checks
            if "float" in code and "Quantity" not in code and "Price" not in code:
                warnings.append("Code may use float instead of Quantity/Price types")
                
            if '"BUY"' in code or '"SELL"' in code:
                warnings.append("Code may use strings instead of OrderSide enum")
                
            return CodeValidationResult(
                is_valid=True,
                errors=errors,
                warnings=warnings
            )
            
        except SyntaxError as e:
            errors.append(f"Syntax error on line {e.lineno}: {e.msg}")
            return CodeValidationResult(
                is_valid=False,
                errors=errors,
                warnings=warnings
            )
        except Exception as e:
            errors.append(f"Validation error: {str(e)}")
            return CodeValidationResult(
                is_valid=False,
                errors=errors,
                warnings=warnings
            )
            
    def generate_config_file(self, config: StrategyConfig, output_path: str):
        """
        Generate strategy configuration file
        
        Args:
            config: Strategy configuration
            output_path: Path to write config file
        """
        import json
        
        config_dict = self._generate_config_dict(config)
        
        with open(output_path, 'w') as f:
            json.dump(config_dict, f, indent=2)
