#!/usr/bin/env python3
"""Create a Paperclip alert when the Impact Gate scan-done finds ungated fix issues.

Called from the impact-gate-scan-done CI workflow when the scan exits non-zero
(meaning one or more done fix issues lack Impact Gate coverage).  Posts a
`medium`-priority issue assigned to the CTO listing the ungated issues.

Usage:
    python scripts/scan_done_alert.py --scan-output <file> [--dry-run]

Exit codes:
    0 — alert issue created (or none needed)
    1 — error
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger("scan_done_alert")

REPO_ROOT = Path(__file__).resolve().parent.parent

CTO_AGENT_ID = "41b5ede6-e209-40ba-b923-dc969c722e6d"
ALERT_LABEL = "impact-gate-alert"


def _setup_session():
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from touch_index.paperclip_client import _board_session, _base, _company

    return _board_session(), _base(), _company()


def _find_todays_alert(
    base_url: str,
    company_id: str,
    sess,
    date_str: str,
) -> dict | None:
    from touch_index.paperclip_client import _paginate

    try:
        candidates = _paginate(
            f"/api/companies/{company_id}/issues",
            {"q": "Impact Gate Scan-Done Alert", "limit": 50},
            page_size=50,
        )
        for issue in candidates:
            title = issue.get("title", "")
            labels = [l.get("name", "") for l in (issue.get("labels") or [])]
            if date_str in title and ALERT_LABEL in labels:
                logger.info(
                    "Found existing alert issue %s: %s",
                    issue.get("identifier", ""),
                    title,
                )
                return issue
        return None
    except Exception as exc:
        logger.warning("Failed to search for existing alerts: %s", exc)
        return None


def create_alert(
    base_url: str,
    company_id: str,
    sess,
    scan_data: dict,
    dry_run: bool,
) -> bool:
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    ungated = scan_data.get("ungated_issues", [])
    ungated_count = scan_data.get("ungated_count", len(ungated))

    if ungated_count == 0:
        logger.info("No ungated issues — no alert needed")
        return True

    existing = _find_todays_alert(base_url, company_id, sess, date_str)
    if existing is not None:
        logger.info(
            "Alert already exists for %s (%s) — skipping duplicate",
            date_str,
            existing.get("identifier", ""),
        )
        return True

    title = f"Impact Gate Scan-Done Alert — {date_str} ({ungated_count} ungated)"

    lines = [
        f"**Daily Impact Gate scan found {ungated_count} done fix issue(s) without gate coverage.**\n",
        "| Identifier | Title |",
        "|---|---|",
    ]
    for issue in ungated:
        lines.append(f"| {issue.get('identifier', '?')} | {issue.get('title', '?')} |")
    lines.append("")

    if scan_data.get("retroactive"):
        lines.append(
            "Retroactive gating was enabled — see `retroactive_results` above.\n"
        )

    lines.append(
        "### Next Steps\n\n"
        "1. Review each ungated issue — determine if manual gate bypass is warranted.\n"
        "2. To retroactively gate: re-run the workflow with `retroactive=true`.\n"
        "3. After gating, the scan-done will report 0 ungated on the next run.\n\n"
        "---\n"
        "_Auto-generated by impact-gate-scan-done CI pipeline._"
    )

    body = "\n".join(lines)

    if dry_run:
        logger.info("DRY RUN: would create alert issue '%s'", title)
        print(  # noqa: T201
            json.dumps(
                {
                    "title": title,
                    "description": body,
                    "labels": [ALERT_LABEL],
                    "assigneeAgentId": CTO_AGENT_ID,
                    "priority": "medium",
                },
                indent=2,
            )
        )
        return True

    payload = {
        "title": title,
        "description": body,
        "labels": [ALERT_LABEL],
        "assigneeAgentId": CTO_AGENT_ID,
        "priority": "medium",
        "status": "todo",
    }

    try:
        resp = sess.post(
            f"{base_url}/api/companies/{company_id}/issues",
            json=payload,
            timeout=30,
        )
        resp.raise_for_status()
        created = resp.json()
        logger.info(
            "Created alert issue %s: %s",
            created.get("identifier", ""),
            title,
        )
        return True
    except Exception as exc:
        logger.error("Failed to create alert issue: %s", exc)
        return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create Paperclip alert when scan-done finds ungated issues",
    )
    parser.add_argument(
        "--scan-output",
        required=True,
        help="Path to JSON file produced by scan_fix_issues_done.py --json-summary",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=None,
        help="Log actions without creating issues (default: follow scan output dry_run field)",
    )
    args = parser.parse_args()

    scan_path = Path(args.scan_output)
    if not scan_path.exists():
        logger.error("Scan output file not found: %s", scan_path)
        sys.exit(1)

    with open(scan_path) as f:
        scan_data = json.load(f)

    # If --dry-run was not explicitly set, respect the scan's own dry_run field
    dry_run = (
        args.dry_run if args.dry_run is not None else scan_data.get("dry_run", False)
    )

    sess, base_url, company_id = _setup_session()

    ok = create_alert(base_url, company_id, sess, scan_data, dry_run)
    if not ok:
        sys.exit(1)

    logger.info("Scan-done alert complete")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    main()
